FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache bash gettext

WORKDIR /usr/share/nginx/html

COPY --from=build /usr/src/app/build /var/www/public
COPY --from=build /usr/src/app/node_modules/@socket.io/admin-ui/ui/dist /var/www/public/socket-admin

COPY nginx /etc/nginx
COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    chmod -R 755 /var/www/public

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
